spring:
  datasource:
    url: 'jdbc:h2:file:./pigs;CASE_INSENSITIVE_IDENTIFIERS=true'
    username: 'sa'
    password: ''
  main:
    web-application-type: servlet

---
spring:
  config:
    activate:
      on-profile: 'test'
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=true'
